JVMCBC-367: Consume and log errors for keepalives.
Motivation
----------
In a recent user log examined it was found that during a socket
close and the cancellation of outstanding requests, one of the
"victims" was a keepalive.

AbstractGenericHandler: Exception thrown while cancelling outstanding operation:
KeepAliveRequest{observable=rx.subjects.AsyncSubject@26424276, bucket='null'}
rx.exceptions.OnErrorNotImplementedException: Request cancelled in-flight.

Modifications
-------------
Since there is not much we can do about it, it at least makes sense to log the
specific condition so that from reading the log it becomes clearer what
happened at runtime.

Result
------
KeepAlives now explicitly handle and log failures on their response side.

Change-Id: Ia964034eec10b771f21ebb73226d0357b458b185
Reviewed-on: http://review.couchbase.org/67737
Tested-by: Michael Nitschinger <michael@nitschinger.at>
Reviewed-by: Subhashni Balakrishnan <b.subhashni@gmail.com>
Reviewed-by: Simon Baslé <simon@couchbase.com>